---
title: "switchgrass_popStruct_imputation"
author: "Colette Berg"
date: "2025-06-19"
output:
  html_document: default
  word_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(dplyr)
library(ggplot2)
```

## reading in the SRA / genotype ID files needed 

```{r sample Sheet, echo=FALSE}
sampleSheet <- read.csv("data/switchgrass_transcriptomics_sample_sheet.csv")

```


```{r, echo=FALSE}
# colnames for all the eigenvec files (generated by plink)
cols <- c("WGS_sample", 
          "SRR2",
          "PC1",
          "PC2",
          "PC3",
          "PC4",
          "PC5",
          "PC6",
          "PC7",
          "PC8",
          "PC9",
          "PC10")
```


## reading in the eigenvalues for chromosome 1 
# starting with the filt_100 group

```{r 100Filt, echo=FALSE}

# read in data 
Chr01K_100 <- read.csv("data/pcas/Chr01K_100_imputed.eigenvec", sep = " ", header = FALSE)

# set col names 
colnames(Chr01K_100) <- cols

# merge with plantID and previously called population

Chr01K_labeled <- merge(sampleSheet, Chr01K_100, id.vars = c("WGS_sample"))

# filt100, Chr 1 
ggplot(Chr01K_labeled,
       aes(x = PC1,
           y = PC2,
           col = subpop)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = c("grey",
                                "brown",
                                "darkorange",
                                "dodgerblue2")) + 
  ggtitle("Chr 1K, 100 filt")
```

```{r, echo=FALSE}
# read in data 
Chr01K_100 <- read.csv("data/pcas/Chr01K_99_imputed.eigenvec", sep = " ", header = FALSE)

# set col names 
colnames(Chr01K_100) <- cols

# merge with plantID and previously called population

Chr01K_labeled <- merge(sampleSheet, Chr01K_100, id.vars = c("WGS_sample"))

# filt100, Chr 1 
ggplot(filter(Chr01K_labeled, plant_ID=="J036.A" |
                                  plant_ID=="J396.A" |
                                  plant_ID=="J525.C" |
                                  plant_ID=="J526.C"),
       aes(x = PC1,
           y = PC2,
           col = subpop,
           label = plant_ID)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = c("brown",
                                "dodgerblue2")) + 
  ggtitle("Chr 1K, 99 filt") +
  geom_label() +
  ylim(0.07, -.07)



```
```{r, echo=FALSE}
# read in data 
Chr01K_100 <- read.csv("data/pcas/Chr01K_97.5_imputed.eigenvec", sep = " ", header = FALSE)

# set col names 
colnames(Chr01K_100) <- cols

# merge with plantID and previously called population

Chr01K_labeled <- merge(sampleSheet, Chr01K_100, id.vars = c("WGS_sample"))

# filt100, Chr 1 
ggplot(Chr01K_labeled,
       aes(x = PC1,
           y = PC2,
           col = subpop)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = c("grey",
                                "brown",
                                "darkorange",
                                "dodgerblue2")) + 
  ggtitle("Chr 1K, 97.5 filt")
```
```{r, echo=FALSE}
# read in data 
Chr01K_100 <- read.csv("data/pcas/Chr01K_95_imputed.eigenvec", sep = " ", header = FALSE)

# set col names 
colnames(Chr01K_100) <- cols

# merge with plantID and previously called population

Chr01K_labeled <- merge(sampleSheet, Chr01K_100, id.vars = c("WGS_sample"))

# filt100, Chr 1 
ggplot(Chr01K_labeled,
       aes(x = PC1,
           y = PC2,
           col = subpop)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = c("grey",
                                "brown",
                                "darkorange",
                                "dodgerblue2")) + 
  ggtitle("Chr 1K, 95 filt")
```
```{r, echo=FALSE}
# read in data 
Chr01K_100 <- read.csv("data/pcas/Chr01K_90_imputed.eigenvec", sep = " ", header = FALSE)

# set col names 
colnames(Chr01K_100) <- cols

# merge with plantID and previously called population

Chr01K_labeled <- merge(sampleSheet, Chr01K_100, id.vars = c("WGS_sample"))

# filt100, Chr 1 
ggplot(Chr01K_labeled,
       aes(x = PC1,
           y = PC2,
           col = subpop)) +
  geom_point() +
  theme_bw() +
  scale_color_manual(values = c("grey",
                                "brown",
                                "darkorange",
                                "dodgerblue2")) + 
  ggtitle("Chr 1K, 90 filt")
```

